/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/signup`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/home` | `/home`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/invester` | `/invester`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/team` | `/team`; params?: Router.UnknownInputParams; } | { pathname: `/home/payment`; params?: Router.UnknownInputParams; } | { pathname: `/home/recharge`; params?: Router.UnknownInputParams; } | { pathname: `/home/rechargehistory`; params?: Router.UnknownInputParams; } | { pathname: `/home/withdrawal`; params?: Router.UnknownInputParams; } | { pathname: `/invest/transfertowithdraw`; params?: Router.UnknownInputParams; } | { pathname: `/invest/viewhistory`; params?: Router.UnknownInputParams; } | { pathname: `/profile/teamfund`; params?: Router.UnknownInputParams; } | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } } | { pathname: `/product/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/signup`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/home` | `/home`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/invester` | `/invester`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/team` | `/team`; params?: Router.UnknownOutputParams; } | { pathname: `/home/payment`; params?: Router.UnknownOutputParams; } | { pathname: `/home/recharge`; params?: Router.UnknownOutputParams; } | { pathname: `/home/rechargehistory`; params?: Router.UnknownOutputParams; } | { pathname: `/home/withdrawal`; params?: Router.UnknownOutputParams; } | { pathname: `/invest/transfertowithdraw`; params?: Router.UnknownOutputParams; } | { pathname: `/invest/viewhistory`; params?: Router.UnknownOutputParams; } | { pathname: `/profile/teamfund`; params?: Router.UnknownOutputParams; } | { pathname: `/+not-found`, params: Router.UnknownOutputParams & {  } } | { pathname: `/product/[id]`, params: Router.UnknownOutputParams & { id: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/signup${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/home${`?${string}` | `#${string}` | ''}` | `/home${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/invester${`?${string}` | `#${string}` | ''}` | `/invester${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/profile${`?${string}` | `#${string}` | ''}` | `/profile${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/team${`?${string}` | `#${string}` | ''}` | `/team${`?${string}` | `#${string}` | ''}` | `/home/payment${`?${string}` | `#${string}` | ''}` | `/home/recharge${`?${string}` | `#${string}` | ''}` | `/home/rechargehistory${`?${string}` | `#${string}` | ''}` | `/home/withdrawal${`?${string}` | `#${string}` | ''}` | `/invest/transfertowithdraw${`?${string}` | `#${string}` | ''}` | `/invest/viewhistory${`?${string}` | `#${string}` | ''}` | `/profile/teamfund${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/signup`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/home` | `/home`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/invester` | `/invester`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/team` | `/team`; params?: Router.UnknownInputParams; } | { pathname: `/home/payment`; params?: Router.UnknownInputParams; } | { pathname: `/home/recharge`; params?: Router.UnknownInputParams; } | { pathname: `/home/rechargehistory`; params?: Router.UnknownInputParams; } | { pathname: `/home/withdrawal`; params?: Router.UnknownInputParams; } | { pathname: `/invest/transfertowithdraw`; params?: Router.UnknownInputParams; } | { pathname: `/invest/viewhistory`; params?: Router.UnknownInputParams; } | { pathname: `/profile/teamfund`; params?: Router.UnknownInputParams; } | `/+not-found` | `/product/${Router.SingleRoutePart<T>}` | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } } | { pathname: `/product/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
    }
  }
}
